import { badge, banner, button, icon, pageHeader, progressBar, routeButton, sectionHeader } from '../components/common.js';
import { SETTINGS_TABS } from '../type.js';
import { escapeHtml } from '../utils.js';

function settingsTabs(active) {
  return '<nav class="settings-tabs" aria-label="Settings sections">' + SETTINGS_TABS.map(function (tab) {
    return '<button type="button" class="settings-tab' + (tab.id === active ? ' is-active' : '') + '" data-route="settings?tab=' + tab.id + '" aria-current="' + (tab.id === active ? 'page' : 'false') + '">' + escapeHtml(tab.label) + '</button>';
  }).join('') + '</nav>';
}

function renderSync(state) {
  const store = state.store;
  const isZh = state.ui.locale === 'zh';
  const text = function (en, zh) { return isZh ? zh : en; };
  const stats = [
    [text('Products', '商品'), store.products, 'products'],
    [text('Variants', '变体'), store.variants, 'products'],
    [text('Discounts', '促销'), store.discounts, 'products'],
    [text('Shipping rates', '运费规则'), store.shippingRates, 'store'],
  ].map(function (item) {
    return '<div class="sync-stat"><span class="sync-stat-icon">' + icon(item[2], 17) + '</span><div><strong>' + escapeHtml(item[1]) + '</strong><small>' + escapeHtml(item[0]) + '</small></div></div>';
  }).join('');
  const history = [
    [text('Shopify access authorized', 'Shopify 授权完成'), text('Scopes verified for products, discounts, shipping and orders.', '商品、促销、运费与订单权限已通过校验。'), '09:31'],
    [text('Checkout workspace created', 'Checkout 工作区已创建'), text('Store, currency and market defaults provisioned.', '已创建店铺、币种与市场默认配置。'), '09:32'],
    [text('Initial commerce data imported', '初始商业数据已同步'), text('Products, variants, promotions and rates were mapped.', '商品、变体、促销与运费规则已完成映射。'), '09:36'],
    [text('Webhook subscriptions registered', 'Webhook 订阅已注册'), text('12 topics are active with signature verification.', '12 个主题已启用签名校验。'), '09:37'],
  ].map(function (item) {
    return '<li class="is-complete"><span>' + icon('check', 14) + '</span><div><strong>' + escapeHtml(item[0]) + '</strong><small>' + escapeHtml(item[1]) + '</small></div><time>' + item[2] + '</time></li>';
  }).join('');
  const installation = '<section class="card installation-card"><div class="card-pad"><div class="installation-card-head"><div><span class="eyebrow">' + escapeHtml(text('Shopify installation', 'Shopify 安装')) + '</span><h2>' + escapeHtml(text('This store’s App instance', '当前店铺的 App 实例')) + '</h2><p>' + escapeHtml(text('BestCheckout uses a merchant-specific Custom-distribution App. This store keeps its own authorization and runtime configuration.', 'BestCheckout 通过商户专属的 Custom distribution App 安装；当前店铺拥有独立授权与运行时配置。')) + '</p></div>' + badge('Complete', text('Installed', '已安装')) + '</div><div class="installation-instance"><span>' + icon('shield', 19) + '</span><div><small>' + escapeHtml(text('Shopify App instance', 'Shopify App 实例')) + '</small><strong data-i18n-skip>' + escapeHtml(store.appInstanceName) + '</strong><code data-i18n-skip>' + escapeHtml(store.appInstanceId) + '</code></div><em>' + escapeHtml(store.distributionMethod) + '</em></div><div class="installation-facts"><div><small>' + escapeHtml(text('Installation scope', '安装范围')) + '</small><strong>' + escapeHtml(text('This store only', '当前店铺')) + '</strong></div><div><small>' + escapeHtml(text('Install source', '安装入口')) + '</small><strong>' + escapeHtml(text('Organization-specific link', '组织专属安装链接')) + '</strong></div><div><small>' + escapeHtml(text('Store authorization', '店铺授权')) + '</small><strong>' + escapeHtml(text('Connected', '已连接')) + '</strong></div></div><button type="button" class="button button-secondary" data-action="show-installation">' + icon('flow', 16) + '<span>' + escapeHtml(text('View installation method', '查看安装方式')) + '</span></button></div></section>';
  return '<div class="settings-stack">'
    + banner('success', text('Store data is synchronized', '店铺数据已同步'), text('BestCheckout created the checkout workspace, mapped Shopify IDs and registered webhooks during authorization.', '授权后，BestCheckout 已自动创建 Checkout 工作区、映射 Shopify ID 并注册 Webhook。'), button(text('Sync now', '立即同步'), 'sync-store', { kind: 'plain', icon: 'sync' }))
    + '<section class="card"><div class="card-pad">' + sectionHeader(text('Shopify connection', 'Shopify 连接'), store.myshopifyDomain, badge(store.status, text('Connected', '已连接'))) + '<dl class="detail-grid"><div><dt>' + escapeHtml(text('Checkout workspace', 'Checkout 工作区')) + '</dt><dd>' + escapeHtml(text('Provisioned', '已开通')) + '</dd></div><div><dt>' + escapeHtml(text('Mapping coverage', '映射覆盖率')) + '</dt><dd>' + escapeHtml(store.mappingCoverage) + '</dd></div><div><dt>' + escapeHtml(text('Webhook health', 'Webhook 健康度')) + '</dt><dd>' + escapeHtml(store.webhookHealth) + '</dd></div><div><dt>' + escapeHtml(text('Last successful sync', '最近同步')) + '</dt><dd>' + escapeHtml(store.lastSync) + '</dd></div></dl><div class="sync-stats">' + stats + '</div></div></section>'
    + installation
    + '<section class="settings-two-col"><div class="card"><div class="card-pad">' + sectionHeader(text('Automatic setup history', '自动开通记录'), text('Completed automatically after Shopify authorization.', '以下步骤在 Shopify 授权后由系统自动完成。')) + '<ol class="setup-history">' + history + '</ol></div></div><aside class="card"><div class="card-pad">' + sectionHeader(text('ID mapping health', 'ID 映射健康度'), text('Shopify IDs stay as the source reference while mapped IDs power checkout execution.', 'Shopify ID 保持为来源参考，映射后的 ID 用于 Checkout 运行。')) + '<div class="mapping-health"><strong>100%</strong><span>' + escapeHtml(store.variants + ' / ' + store.variants + ' ' + text('active variants mapped', '个活跃变体已映射')) + '</span>' + progressBar(100, 'success') + '</div><div class="mapping-list"><div><span>' + escapeHtml(text('Missing products', '缺失商品')) + '</span><strong>0</strong></div><div><span>' + escapeHtml(text('Stale variants', '过期变体')) + '</span><strong>0</strong></div><div><span>' + escapeHtml(text('Webhook backlog', 'Webhook 积压')) + '</span><strong>0</strong></div></div><button type="button" class="button button-secondary button-block" data-action="download-mapping-report">' + escapeHtml(text('Download mapping report', '下载映射报告')) + '</button></div></aside></section></div>';
}

function renderDomainLegacy(state) {
  const store = state.store;
  const host = store.domain.split('.')[0] || 'checkout';
  const rootDomain = store.domain.split('.').slice(1).join('.') || 'yourstore.com';
  return '<div class="settings-stack"><section class="card domain-hero"><div class="card-pad"><div class="domain-hero-top"><span class="domain-icon">' + icon('globe', 24) + '</span><div><span class="eyebrow">Checkout domain</span><h2 data-i18n-skip>' + escapeHtml(store.domain) + '</h2><p>This is the address buyers see when they move from your store to checkout.</p></div>' + badge(store.domainStatus) + '</div><div class="domain-setup"><div class="domain-setup-head"><div><strong>Connect your checkout subdomain</strong><small>Add this record with the company that manages ' + escapeHtml(rootDomain) + '.</small></div>' + button('Change domain', 'change-domain', { kind: 'plain' }) + '</div><div class="dns-record"><div><small>Record type</small><strong>CNAME</strong></div><div><small>Host / name</small><code data-i18n-skip>' + escapeHtml(host) + '</code></div><div><small>Points to</small><code data-i18n-skip>shops.bestcheckout.app</code></div><div><small>TTL</small><strong>Auto</strong></div><button type="button" class="button button-secondary" data-action="copy-dns-record">' + icon('copy', 16) + '<span>Copy record</span></button></div><ol class="numbered-steps domain-steps"><li><span>1</span><div><strong>Add the CNAME record</strong><small>Use the host and target shown above in your DNS provider.</small></div></li><li><span>2</span><div><strong>Wait for DNS to update</strong><small>This can take a few minutes, depending on your DNS provider.</small></div></li><li><span>3</span><div><strong>Verify your domain</strong><small>BestCheckout will enable SSL after the record is found.</small></div></li></ol></div><div class="inline-actions">' + button('Verify DNS', 'verify-domain', { icon: 'sync' }) + '</div></div></section><section class="card"><div class="card-pad">' + sectionHeader('Checkout address', 'Buyers start on your Shopify store and continue on your branded checkout domain.') + '<div class="url-pattern"><span>Shopify store</span><code data-i18n-skip>https://www.lavenderlabs.co/cart</code><i>' + icon('arrow', 17) + '</i><span>Buyer checkout</span><code data-i18n-skip>https://' + escapeHtml(store.domain) + '/c/••••</code></div></div></section></div>';
}

function renderDomain(state) {
  const store = state.store;
  const isZh = state.ui.locale === 'zh';
  const host = store.domain.split('.')[0] || 'checkout';
  const rootDomain = store.domain.split('.').slice(1).join('.') || 'yourstore.com';
  const manual = state.ui.domainSetupMode === 'manual';
  const provider = store.dnsProvider || 'Cloudflare';
  const connection = store.domainConnection || 'Not connected';
  const automaticPath = '<article class="setup-path setup-path-recommended"><header><span class="setup-path-icon">' + icon('sparkles', 18) + '</span><div><strong>Connect your DNS provider</strong><small>Recommended · no record copying</small></div><em>Recommended</em></header><p>Sign in to your DNS provider once. BestCheckout adds this checkout record, monitors DNS and provisions SSL automatically.</p><div class="setup-path-meta"><span>' + icon('shield', 15) + ' Provider access is limited to this record</span><span>' + icon('check', 15) + ' SSL is issued automatically</span></div>' + button(connection === 'Connected' ? 'Manage provider connection' : 'Connect DNS provider', 'connect-dns-provider', { kind: 'primary', icon: 'external' }) + '</article>';
  const manualPath = '<article class="setup-path"><header><span class="setup-path-icon">' + icon('settings', 18) + '</span><div><strong>Add a DNS record yourself</strong><small>Use this when your provider is not available for secure connection.</small></div></header><p>You only need to add one CNAME record. BestCheckout keeps checking and creates SSL as soon as it is found.</p>' + button('Show CNAME record', 'show-manual-domain-setup', { kind: 'secondary', icon: 'settings' }) + '</article>';
  const manualDetails = '<div class="manual-domain-details"><div class="dns-record"><div><small>Record type</small><strong>CNAME</strong></div><div><small>Host / name</small><code data-i18n-skip>' + escapeHtml(host) + '</code></div><div><small>Points to</small><code data-i18n-skip>shops.bestcheckout.app</code></div><div><small>TTL</small><strong>Auto</strong></div><button type="button" class="button button-secondary" data-action="copy-dns-record">' + icon('copy', 16) + '<span>Copy record</span></button></div><p class="helper-copy">Paste this record in the service that manages <strong data-i18n-skip>' + escapeHtml(rootDomain) + '</strong>. You do not need to configure certificates or callbacks.</p></div>';
  const connectionState = connection === 'Connected'
    ? '<div class="domain-connected-status">' + icon('check', 16) + '<span><strong>' + escapeHtml(provider) + ' is connected</strong><small>BestCheckout is monitoring DNS and SSL for ' + escapeHtml(store.domain) + '.</small></span></div>'
    : '';
  return '<div class="settings-stack"><section class="card domain-hero"><div class="card-pad"><div class="domain-hero-top"><span class="domain-icon">' + icon('globe', 24) + '</span><div><span class="eyebrow">' + (isZh ? 'Checkout 域名' : 'Checkout domain') + '</span><h2 data-i18n-skip>' + escapeHtml(store.domain) + '</h2><p>' + (isZh ? '这是买家从店铺进入 Checkout 时看到的地址。' : 'This is the address buyers see when they move from your store to checkout.') + '</p></div>' + badge(store.domainStatus) + '</div><div class="setup-assist"><span>' + icon('play', 17) + '</span><div><strong>Keep building while your domain is being connected</strong><small>' + (isZh ? '使用 ' : 'Use ') + '<code data-i18n-skip>' + escapeHtml(store.previewDomain || 'lavender-labs.preview.bestcheckout.app') + '</code>' + (isZh ? ' 进行安全预览。只有开始向真实买家分配流量前，才必须完成品牌域名解析。' : ' for safe previews. Branded DNS is required only before sending live traffic.') + '</small></div><button type="button" class="button button-plain" data-action="copy-preview-domain">Copy preview address</button></div><div class="domain-setup"><div class="domain-setup-head"><div><strong>' + (isZh ? '连接 ' + escapeHtml(rootDomain) + ' 的域名' : 'Choose how to connect ' + escapeHtml(rootDomain)) + '</strong><small>Most merchants finish the only required action by securely authorizing their DNS provider.</small></div>' + button('Change domain', 'change-domain', { kind: 'plain' }) + '</div><div class="setup-path-grid">' + automaticPath + manualPath + '</div>' + (manual ? manualDetails : '') + connectionState + '<div class="inline-actions">' + button(store.domainStatus === 'Verified' ? 'DNS verified' : 'Check connection', 'verify-domain', { icon: 'sync', kind: store.domainStatus === 'Verified' ? 'secondary' : 'primary' }) + (manual ? button('Use automatic setup instead', 'show-automatic-domain-setup', { kind: 'plain' }) : '') + '</div></div></div></section><section class="card"><div class="card-pad">' + sectionHeader(isZh ? '买家看到的地址' : 'Checkout address', isZh ? '买家从 Shopify 店铺出发，并在你的品牌 Checkout 域名中完成结账。' : 'Buyers start on your Shopify store and continue on your branded checkout domain.') + '<div class="url-pattern"><span>' + (isZh ? 'Shopify 店铺' : 'Shopify store') + '</span><code data-i18n-skip>https://www.lavenderlabs.co/cart</code><i>' + icon('arrow', 17) + '</i><span>' + (isZh ? '买家 Checkout' : 'Buyer checkout') + '</span><code data-i18n-skip>https://' + escapeHtml(store.domain) + '/c/••••</code></div></div></section></div>';
}

function capabilityBadge(value) {
  return badge(value);
}

function renderPaymentsLegacy(state) {
  const providerCards = state.providers.map(function (provider) {
    const actionLabel = provider.status === 'Connected' ? 'Manage' : 'Join waitlist';
    const action = provider.status === 'Connected' ? 'manage-provider' : 'waitlist-provider';
    return '<article class="provider-card"><header><span class="provider-logo provider-' + escapeHtml(provider.id) + '" data-i18n-skip>' + escapeHtml(provider.name.charAt(0)) + '</span><div data-i18n-skip><strong>' + escapeHtml(provider.name) + '</strong><small>' + escapeHtml(provider.account) + '</small></div>' + badge(provider.status) + '</header><dl><div><dt>Payment methods</dt><dd>' + escapeHtml(provider.methods) + '</dd></div><div><dt>Regions</dt><dd>' + escapeHtml(provider.regions) + '</dd></div><div><dt>Post-purchase summary</dt><dd>' + capabilityBadge(provider.postPurchase) + '</dd></div><div><dt>Last 30 days</dt><dd>' + escapeHtml(provider.capabilityCoverage) + '</dd></div></dl><p>' + escapeHtml(provider.notes) + '</p><footer><span>' + (provider.successRate === '—' ? 'Not processing traffic' : escapeHtml(provider.successRate) + ' payment success') + '</span><button type="button" class="button button-plain" data-action="' + action + '" data-provider-id="' + escapeHtml(provider.id) + '">' + escapeHtml(actionLabel) + '</button></footer></article>';
  }).join('');
  const rows = state.providers.flatMap(function (provider) {
    return provider.capabilityEvaluations.map(function (evaluation) {
      return '<tr><td><strong data-i18n-skip>' + escapeHtml(provider.name) + '</strong></td><td>' + escapeHtml(evaluation.method) + '</td><td>' + escapeHtml(evaluation.region + ' · ' + evaluation.currency) + '</td><td>' + escapeHtml(evaluation.authorizationState) + '</td><td>' + capabilityBadge(evaluation.outcome) + '</td><td>' + escapeHtml(evaluation.confirmationFlow) + '</td><td><code data-i18n-skip>' + escapeHtml(evaluation.reasonCode) + '</code></td></tr>';
    });
  }).join('');
  return '<div class="settings-stack">' + banner('info', 'Post-purchase eligibility is evaluated per transaction', 'Unsupported methods and failures before an additional charge are safe skips. After an additional charge succeeds, snapshot or writeback failures enter reconciliation and must not be skipped.', button('View runtime rules', 'show-capability-rules', { kind: 'plain' })) + '<section><div class="section-header outside-card"><div><h2>Payment providers</h2><p>BestCheckout stores secure connection references, never raw card data or copied Shopify credentials.</p></div>' + button('Connect provider', 'connect-provider', { kind: 'primary', icon: 'plus' }) + '</div><div class="provider-grid">' + providerCards + '</div></section><section class="card"><div class="card-pad">' + sectionHeader('Capability evaluations', 'Provider connection alone never proves post-purchase support; the backend evaluates the concrete transaction combination.') + '</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Provider</th><th>Method</th><th>Market</th><th>Authorization</th><th>Outcome</th><th>Confirmation</th><th>Reason</th></tr></thead><tbody>' + rows + '</tbody></table></div></section></div>';
}

function renderPayments(state) {
  const isZh = state.ui.locale === 'zh';
  const providerCards = state.providers.map(function (provider) {
    const connectable = provider.status === 'Action required';
    const actionLabel = provider.status === 'Connected' ? (isZh ? '管理连接' : 'Manage connection') : connectable ? (isZh ? '连接账户' : 'Connect account') : (isZh ? '加入等候名单' : 'Join waitlist');
    const action = provider.status === 'Connected' ? 'manage-provider' : connectable ? 'connect-provider' : 'waitlist-provider';
    const account = provider.account === 'Not connected' && isZh ? '未连接' : provider.account;
    const coverage = provider.capabilityCoverage === 'Connect an account to evaluate' && isZh ? '连接账户后评估' : provider.capabilityCoverage;
    const processing = provider.successRate === '—' ? (isZh ? '尚未处理流量' : 'Not processing traffic') : escapeHtml(provider.successRate) + (isZh ? ' 支付成功率' : ' payment success');
    return '<article class="provider-card"><header><span class="provider-logo provider-' + escapeHtml(provider.id) + '" data-i18n-skip>' + escapeHtml(provider.name.charAt(0)) + '</span><div data-i18n-skip><strong>' + escapeHtml(provider.name) + '</strong><small>' + escapeHtml(account) + '</small></div>' + badge(provider.status) + '</header><dl><div><dt>Payment methods</dt><dd>' + escapeHtml(provider.methods) + '</dd></div><div><dt>Regions</dt><dd>' + escapeHtml(provider.regions) + '</dd></div><div><dt>Post-purchase summary</dt><dd>' + capabilityBadge(provider.postPurchase) + '</dd></div><div><dt>Last 30 days</dt><dd>' + escapeHtml(coverage) + '</dd></div></dl><p>' + escapeHtml(provider.notes) + '</p><footer><span>' + processing + '</span><button type="button" class="button button-plain" data-action="' + action + '" data-provider-id="' + escapeHtml(provider.id) + '">' + escapeHtml(actionLabel) + '</button></footer></article>';
  }).join('');
  const rows = state.providers.flatMap(function (provider) {
    return provider.capabilityEvaluations.map(function (evaluation) {
      return '<tr><td><strong data-i18n-skip>' + escapeHtml(provider.name) + '</strong></td><td>' + escapeHtml(evaluation.method) + '</td><td>' + escapeHtml(evaluation.region + ' · ' + evaluation.currency) + '</td><td>' + escapeHtml(evaluation.authorizationState) + '</td><td>' + capabilityBadge(evaluation.outcome) + '</td><td>' + escapeHtml(evaluation.confirmationFlow) + '</td><td><code data-i18n-skip>' + escapeHtml(evaluation.reasonCode) + '</code></td></tr>';
    });
  }).join('');
  const setup = '<section class="card payment-setup"><div class="card-pad"><div class="payment-setup-head"><div><span class="eyebrow">Fast setup</span><h2>Connect a payment account — webhook handled for you</h2><p>BestCheckout chooses the lowest-friction connection the provider supports: secure authorization when available, or only the single credential required when it is not. It registers signed webhooks and runs the first connection check.</p></div>' + button('Connect payment account', 'connect-provider', { kind: 'primary', icon: 'plus' }) + '</div><div class="connection-flow"><div><span>1</span><strong>Choose provider</strong><small>Use the account that receives your checkout payments.</small></div><i>' + icon('arrow', 17) + '</i><div><span>2</span><strong>Authorize or add one credential</strong><small>BestCheckout detects the safest connection method for that provider.</small></div><i>' + icon('arrow', 17) + '</i><div><span>3</span><strong>BestCheckout validates</strong><small>Webhook, payment methods and a safe test are prepared automatically.</small></div></div><p class="payment-setup-footnote">Merchants never configure webhook URLs or signatures by hand. If a gateway lacks secure authorization, BestCheckout asks only for the credential it needs and stores it in the connection vault.</p></div></section>';
  return '<div class="settings-stack">' + setup + banner('info', 'Post-purchase eligibility is evaluated per transaction', 'Unsupported methods and failures before an additional charge are safe skips. After an additional charge succeeds, snapshot or writeback failures enter reconciliation and must not be skipped.', button('View runtime rules', 'show-capability-rules', { kind: 'plain' })) + '<section><div class="section-header outside-card"><div><h2>Payment providers</h2><p>Each connection shows its merchant ownership and post-purchase capability separately.</p></div>' + button('Connect provider', 'connect-provider', { kind: 'primary', icon: 'plus' }) + '</div><div class="provider-grid">' + providerCards + '</div></section><section class="card"><div class="card-pad">' + sectionHeader('Capability evaluations', 'Provider connection alone never proves post-purchase support; the backend evaluates the concrete transaction combination.') + '</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Provider</th><th>Method</th><th>Market</th><th>Authorization</th><th>Outcome</th><th>Confirmation</th><th>Reason</th></tr></thead><tbody>' + rows + '</tbody></table></div></section></div>';
}

function renderAttribution(state) {
  const rows = state.tracking.map(function (item) {
    return '<tr><td><div class="tracking-name"><span class="tracking-icon">' + icon(item.id === 'bestcheckout' ? 'sparkles' : 'pixel', 16) + '</span><div data-i18n-skip><strong>' + escapeHtml(item.name) + '</strong><small>' + escapeHtml(item.discoveredId + ' · ' + item.discoveredFrom) + '</small></div></div></td><td>' + escapeHtml(item.ownershipState) + '</td><td>' + escapeHtml(item.browserConfigState) + '</td><td>' + escapeHtml(item.serverAuthState) + '</td><td>' + escapeHtml(item.consentState) + '</td><td>' + escapeHtml(item.testState) + '</td><td>' + badge(item.state) + '</td></tr>';
  }).join('');
  return '<div class="settings-stack">' + banner('warning', 'Discovery is not authorization', 'BestCheckout found Meta, GA4 and GTM identifiers in the storefront HTML. Ownership confirmation, browser configuration, server authorization, consent mapping and delivery tests remain independent states.', button('Review discovered tags', 'review-tags', { kind: 'plain' })) + '<section class="card"><div class="card-pad">' + sectionHeader('Tracking connections', 'Browser and server delivery must share event_id ownership to prevent duplicate purchases.', button('Run event test', 'run-event-test', { icon: 'play' })) + '</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Destination</th><th>Ownership</th><th>Browser config</th><th>Server auth</th><th>Consent</th><th>Test</th><th>Status</th></tr></thead><tbody>' + rows + '</tbody></table></div></section><section class="card"><div class="card-pad">' + sectionHeader('Attribution handoff', 'The same identity envelope follows the shopper from Shopify storefront to BestCheckout and back.') + '<div class="attribution-flow"><div><span>' + icon('store', 19) + '</span><strong>Shopify storefront</strong><small>UTM · click IDs · consent</small></div><i>' + icon('arrow', 18) + '</i><div><span>' + icon('card', 19) + '</span><strong>BestCheckout</strong><small>funnel_id · event_id · payment</small></div><i>' + icon('arrow', 18) + '</i><div><span>' + icon('orders', 19) + '</span><strong>Final order</strong><small>revenue · offers · channel</small></div><i>' + icon('arrow', 18) + '</i><div><span>' + icon('pixel', 19) + '</span><strong>Destinations</strong><small>Browser + server deduped</small></div></div><div class="contract-list"><div><strong>One purchase owner</strong><span>Final Order Snapshot emits the terminal purchase after all accepted post-purchase changes.</span></div><div><strong>One event ID</strong><span>Browser and server copies use the same deterministic event_id for channel deduplication.</span></div><div><strong>Consent travels with the session</strong><span>Customer Privacy state is captured before handoff and enforced on the hosted origin.</span></div></div></div></section></div>';
}

function renderEmbed(state) {
  const store = state.store;
  const entryChecks = store.embedEntryChecks.map(function (item) {
    return '<div class="guardrail-row"><span>' + escapeHtml(item.target) + '</span>' + badge(item.state) + '</div>';
  }).join('');
  return '<div class="settings-stack">' + banner('success', 'BestCheckout is enabled on your active theme', 'When you change or publish a theme, come back here and verify it again.', button('Verify again', 'verify-app-embed', { kind: 'plain', icon: 'sync' })) + '<section class="settings-two-col"><div class="card"><div class="card-pad">' + sectionHeader('Current theme', 'BestCheckout is currently connected to this Shopify theme.') + '<dl class="detail-grid detail-grid-single"><div><dt>Active theme</dt><dd data-i18n-skip>' + escapeHtml(store.activeTheme) + '</dd></div><div><dt>BestCheckout status</dt><dd>' + badge(store.appEmbed) + '</dd></div><div><dt>Last verified</dt><dd>' + escapeHtml(store.embedVerifiedAt) + '</dd></div></dl><button type="button" class="button button-secondary" data-action="open-theme-editor">' + icon('external', 16) + '<span>Open Shopify Theme Editor</span></button></div></div><aside class="card"><div class="card-pad">' + sectionHeader('How to enable BestCheckout', 'You only need to do this once for each new theme.') + '<ol class="numbered-steps"><li><span>1</span><div><strong>Open Online Store → Themes</strong><small>Customize the theme you want to use.</small></div></li><li><span>2</span><div><strong>Open App embeds</strong><small>Find BestCheckout in the left panel.</small></div></li><li><span>3</span><div><strong>Turn on BestCheckout and save</strong><small>Return here and choose Verify again.</small></div></li></ol></div></aside></section><section class="card"><div class="card-pad">' + sectionHeader('Supported checkout buttons', 'These storefront buttons are ready for your current theme.') + '<div class="guardrail-list">' + entryChecks + '</div></div></section></div>';
}

function renderDiagnostics(state) {
  const store = state.store;
  const checks = [
    ['Shopify hosted access', store.distributionStatus, store.distributionMode + ', ' + store.shopifyPlan + ' plan eligibility, merchant authorization and ' + store.targetRegions.join('/') + ' region eligibility are approved.'],
    ['Cart handoff authority', store.cartHandoffValidation, 'Payload parity, TTL and authoritative inventory, price, discount, shipping, tax and duty refresh passed.'],
    ['Checkout domain', 'Verified', 'DNS, SSL and canonical origin checks passed.'],
    ['Payment routing', 'Healthy', 'The Funnel route pins provider connection references and transaction capability dimensions.'],
    ['Post-purchase capability', 'Healthy', 'Runtime method and region checks are enabled.'],
    ['Tracking and consent', 'Action required', 'Review Meta server authorization and GTM consent behavior.'],
    ['Order writeback', 'Healthy', store.writebackCreateSuccessRate + '% create success · backlog ' + store.writebackBacklog + ' · oldest ' + store.writebackOldestAgeMinutes + ' min.'],
    ['Writeback circuit', store.writebackCircuitState, store.writebackCircuitState === 'Open' ? 'New hosted sessions route to Shopify native before payment; paid orders continue reconciliation.' : 'New hosted sessions are allowed; thresholds remain enforced continuously.'],
    ['App embed', 'Verified', 'Theme snapshot and cart page, drawer, Buy now, third-party button and payload parity checks passed.'],
  ].map(function (item) {
    return '<div class="diagnostic-row"><span class="diagnostic-state">' + icon(['Action required', 'Open', 'Blocked'].includes(item[1]) ? 'alert' : 'check', 15) + '</span><div><strong>' + escapeHtml(item[0]) + '</strong><small>' + escapeHtml(item[2]) + '</small></div>' + badge(item[1]) + '</div>';
  }).join('');
  const circuitAction = store.writebackCircuitState === 'Open'
    ? button('Restore mock health', 'restore-writeback-health', { kind: 'secondary', icon: 'sync' })
    : button('Test circuit', 'run-circuit-drill', { kind: 'secondary', icon: 'shield' });
  const diagnosticActions = '<div class="inline-actions">' + circuitAction + button('Run all checks', 'run-diagnostics', { kind: 'primary', icon: 'play' }) + '</div>';
  return '<div class="settings-stack"><section class="card"><div class="card-pad">' + sectionHeader('Store status', 'Last checked: ' + state.ui.diagnosticsRanAt, diagnosticActions) + '<div class="diagnostic-list">' + checks + '</div></div></section></div>';
}

export function renderSettings(state, route) {
  const requested = route.query.get('tab') || 'sync';
  const active = SETTINGS_TABS.some(function (tab) { return tab.id === requested; }) ? requested : 'sync';
  const header = pageHeader('Settings', 'Manage the Shopify connection, checkout runtime and deployment health.');
  let content = renderSync(state);
  if (active === 'domain') content = renderDomain(state);
  if (active === 'payments') content = renderPayments(state);
  if (active === 'attribution') content = renderAttribution(state);
  if (active === 'embed') content = renderEmbed(state);
  if (active === 'diagnostics') content = renderDiagnostics(state);
  return '<div class="page-stack">' + header + settingsTabs(active) + content + '</div>';
}
