import { CAPABILITY, FUNNEL_STATUS, PAGE_TYPE, PROVIDER_STATUS } from './type.js';

const PAYMENT_ROUTE_BINDINGS = [
  { providerId: 'stripe', connectionRef: 'provider_connection_stripe', merchantAccountRef: 'merchant_stripe_us_4821', regions: ['US', 'CA'], currencies: ['USD', 'CAD'], methods: ['card', 'apple_pay', 'google_pay'], authorizationState: 'Verified', testPaymentState: 'Passed', webhookState: 'Verified', status: 'Verified' },
  { providerId: 'airwallex', connectionRef: 'provider_connection_airwallex', merchantAccountRef: 'merchant_airwallex_global_2140', regions: ['US', 'CA'], currencies: ['USD', 'CAD'], methods: ['card', 'apple_pay', 'google_pay'], authorizationState: 'Verified', testPaymentState: 'Passed', webhookState: 'Verified', status: 'Verified' },
  { providerId: 'paypal', connectionRef: 'provider_connection_paypal', merchantAccountRef: 'merchant_paypal_lavenderlabs', regions: ['US', 'CA'], currencies: ['USD', 'CAD'], methods: ['paypal'], authorizationState: 'Verified', testPaymentState: 'Passed', webhookState: 'Verified', status: 'Verified' },
];

const OFFER_VERSIONS = [
  { id: 'offer_night_routine_v3', schemaVersion: 'bestcheckout.offer.v1', status: 'Published', kind: 'upsell', trigger: { after: 'base_payment_captured' }, targetVariantId: 'bs_variant_night_gummies_60', pricing: { type: 'fixed', currency: 'USD', amount: '19.20' }, inventoryPolicyRef: 'inventory_authoritative_v1', markets: ['US', 'CA'], paymentEligibilityPolicyRef: 'postpurchase_runtime_v2' },
  { id: 'offer_travel_fallback_v2', schemaVersion: 'bestcheckout.offer.v1', status: 'Published', kind: 'downsell', trigger: { after: 'upsell_declined' }, targetVariantId: 'bs_variant_travel_gummies_20', pricing: { type: 'fixed', currency: 'USD', amount: '9.60' }, inventoryPolicyRef: 'inventory_authoritative_v1', markets: ['US', 'CA'], paymentEligibilityPolicyRef: 'postpurchase_runtime_v2' },
  { id: 'offer_refill_v2', schemaVersion: 'bestcheckout.offer.v1', status: 'Published', kind: 'upsell', trigger: { after: 'base_payment_captured' }, targetVariantId: 'bs_variant_refill_60', pricing: { type: 'fixed', currency: 'USD', amount: '17.40' }, inventoryPolicyRef: 'inventory_authoritative_v1', markets: ['US', 'CA'], paymentEligibilityPolicyRef: 'postpurchase_runtime_v2' },
];

const RECOMMENDATION_RULE_VERSIONS = [
  { id: 'recommend_sleep_bundle_v2', schemaVersion: 'bestcheckout.recommendation.v1', status: 'Published', strategy: 'manual_priority', sourceProductIds: ['bs_product_sleep_reset'], candidateOfferVersionIds: ['offer_night_routine_v3', 'offer_refill_v2'], markets: ['US', 'CA'] },
  { id: 'recommend_travel_size_v1', schemaVersion: 'bestcheckout.recommendation.v1', status: 'Published', strategy: 'decline_recovery', sourceProductIds: ['bs_product_sleep_reset'], candidateOfferVersionIds: ['offer_travel_fallback_v2'], markets: ['US', 'CA'] },
];

const OFFER_CATALOG_VARIANTS = [
  { id: 'bs_variant_night_gummies_60', name: 'Nighttime Gummies · 60 count', mapped: true, inventoryState: 'Available', currencies: ['USD', 'CAD'], markets: ['US', 'CA'] },
  { id: 'bs_variant_travel_gummies_20', name: 'Travel Gummies · 20 count', mapped: true, inventoryState: 'Available', currencies: ['USD', 'CAD'], markets: ['US', 'CA'] },
  { id: 'bs_variant_refill_60', name: 'Sleep Reset Refill · 60 count', mapped: true, inventoryState: 'Available', currencies: ['USD', 'CAD'], markets: ['US', 'CA'] },
];

const OFFER_SOURCE_PRODUCTS = [
  { id: 'bs_product_sleep_reset', name: 'Sleep Reset Starter Kit' },
  { id: 'bs_product_cart_context', name: 'Any paid cart' },
];

const PAGE_ASSETS = [
  {
    id: 'page-aura-checkout',
    name: 'Aura checkout',
    type: PAGE_TYPE.CHECKOUT,
    status: 'Published',
    version: 12,
    publishedVersionId: 'pv_checkout_12',
    revisionSequence: 18,
    draftRevisionId: null,
    draftRevision: null,
    updated: '18 min ago',
    usedBy: 2,
    metricLabel: 'Completion rate',
    metric: '61.8%',
    change: '+4.2 pts',
    accent: '#6d5dfc',
  },
  {
    id: 'page-night-routine',
    name: 'Night routine offer',
    type: PAGE_TYPE.UPSELL,
    status: 'Published',
    version: 8,
    publishedVersionId: 'pv_upsell_8',
    revisionSequence: 11,
    draftRevisionId: null,
    draftRevision: null,
    updated: 'Yesterday',
    usedBy: 1,
    metricLabel: 'Take rate',
    metric: '18.6%',
    change: '+2.8 pts',
    accent: '#303030',
  },
  {
    id: 'page-travel-fallback',
    name: 'Travel size fallback',
    type: PAGE_TYPE.DOWNSELL,
    status: 'Draft changes',
    version: 5,
    publishedVersionId: 'pv_downsell_5',
    revisionSequence: 1,
    draftRevisionId: 'rev_downsell_1',
    draftRevision: 1,
    updated: '2 hours ago',
    usedBy: 1,
    metricLabel: 'Recovery rate',
    metric: '9.4%',
    change: '+1.1 pts',
    accent: '#d97706',
  },
  {
    id: 'page-aura-thankyou',
    name: 'Aura thank you',
    type: PAGE_TYPE.THANK_YOU,
    status: 'Published',
    version: 10,
    publishedVersionId: 'pv_thankyou_10',
    revisionSequence: 14,
    draftRevisionId: null,
    draftRevision: null,
    updated: '3 days ago',
    usedBy: 2,
    metricLabel: 'Referral click rate',
    metric: '7.2%',
    change: '+0.6 pts',
    accent: '#29845a',
  },
  {
    id: 'page-express-checkout',
    name: 'Express checkout',
    type: PAGE_TYPE.CHECKOUT,
    status: 'Draft',
    version: 0,
    publishedVersionId: null,
    revisionSequence: 3,
    draftRevisionId: 'rev_express_3',
    draftRevision: 3,
    updated: 'Jul 12',
    usedBy: 0,
    metricLabel: 'Completion rate',
    metric: '—',
    change: 'Not live',
    accent: '#005bd3',
  },
];

const FUNNELS = [
  {
    id: 'funnel-sleep-reset',
    name: 'Sleep Reset',
    status: FUNNEL_STATUS.DRAFT,
    priority: 10,
    conflictPolicy: 'first_match_by_priority',
    audience: 'US & CA · cart over $60 · returning customers',
    hostedTraffic: 10,
    nativeTraffic: 90,
    sessions: '—',
    conversion: '—',
    aov: '—',
    revenue: '—',
    updated: 'Not published',
    rules: [
      'Market is United States or Canada',
      'Cart total is at least $60',
      'Customer has placed at least 1 order',
    ],
    audienceConditions: [
      { field: 'country', operator: 'is', value: 'United States, Canada' },
      { field: 'cart_total', operator: 'at_least', value: '$60' },
      { field: 'past_orders', operator: 'at_least', value: '1' },
    ],
    draftRevisionSequence: 12,
    draftRevisionId: 'fr_funnel-sleep-reset_12',
    allocationVersion: 4,
    bucketSeed: 'bucket_sleep_reset_v1',
    paymentRoutePolicyRef: 'payroute_primary_2026_07',
    paymentRouteProviderIds: ['stripe', 'airwallex', 'paypal'],
    paymentRouteBindings: PAYMENT_ROUTE_BINDINGS,
    requiredPaymentMethods: ['card', 'paypal'],
    postPurchaseCapabilityPolicyRef: 'postpurchase_runtime_v2',
    fallbackPolicyRef: 'phase_aware_checkout_recovery_v2',
    trackingContractVersion: 'bestcheckout.tracking.v1',
    nodes: [
      { id: 'shopify-cart', kind: 'entry', label: 'Shopify cart', detail: 'Eligible traffic', state: 'Healthy' },
      { id: 'checkout-main', kind: 'checkout', label: 'Aura checkout', detail: 'Draft matches live deployment', pageId: 'page-aura-checkout', state: 'Ready' },
      { id: 'upsell-night', kind: 'upsell', label: 'Night routine offer', detail: 'Draft matches live deployment', pageId: 'page-night-routine', state: 'Ready', offerRuleRef: 'offer_night_routine_v3', recommendationRuleRef: 'recommend_sleep_bundle_v2' },
      { id: 'downsell-travel', kind: 'downsell', label: 'Travel fallback', detail: 'Page draft r1 available', pageId: 'page-travel-fallback', state: 'Ready', offerRuleRef: 'offer_travel_fallback_v2', recommendationRuleRef: 'recommend_travel_size_v1' },
      { id: 'thankyou-main', kind: 'thank-you', label: 'Aura thank you', detail: 'Draft matches live deployment', pageId: 'page-aura-thankyou', state: 'Ready' },
    ],
    graphEdges: [
      { from: 'shopify-cart', to: 'checkout-main', outcome: 'eligible_hosted_bucket' },
      { from: 'shopify-cart', to: 'shopify-native-checkout', outcome: 'native_control_or_fallback' },
      { from: 'checkout-main', to: 'upsell-night', outcome: 'checkout_completed_offer_eligible' },
      { from: 'checkout-main', to: 'thankyou-main', outcome: 'offer_ineligible_or_skipped' },
      { from: 'upsell-night', to: 'thankyou-main', outcome: 'accepted' },
      { from: 'upsell-night', to: 'downsell-travel', outcome: 'declined' },
      { from: 'upsell-night', to: 'thankyou-main', outcome: 'unavailable_or_skipped' },
      { from: 'downsell-travel', to: 'thankyou-main', outcome: 'accepted' },
      { from: 'downsell-travel', to: 'thankyou-main', outcome: 'declined' },
      { from: 'downsell-travel', to: 'thankyou-main', outcome: 'unavailable_or_skipped' },
    ],
    guardrails: {
      traffic: 'Ready',
      pages: 'Ready',
      graph: 'Ready',
      payment: 'Ready',
      inventory: 'Ready',
      tracking: 'Review needed',
      writeback: 'Ready',
      shopifyAccess: 'Ready',
      domain: 'Ready',
      embed: 'Ready',
      fallback: 'Shopify native before payment',
    },
    guardrailSeverity: { traffic: 'block', pages: 'block', graph: 'block', payment: 'block', inventory: 'block', tracking: 'warn', writeback: 'block', shopifyAccess: 'block', domain: 'block', embed: 'block' },
    deploymentCheck: { expectedRevision: 'fr_funnel-sleep-reset_12', checkedPayloadHash: 'payload_sleep_reset_12', snapshotHash: 'payload_sleep_reset_12', idempotencyKey: 'publish:funnel-sleep-reset:fr_funnel-sleep-reset_12:payload_sleep_reset_12', checkedAt: '8 min ago' },
    runtimeTraffic: { hosted: 0, native: 100 },
    currentDeploymentId: 'deploy_sleep_reset_12',
    deploymentHistory: [],
    deploymentSnapshot: {
      schemaVersion: 'bestcheckout.funnel-deployment.v1',
      id: 'deploy_sleep_reset_12',
      sourceFunnelRevision: 'fr_funnel-sleep-reset_12',
      sourceFunnelRevisionSequence: 12,
      surface: {
        mode: 'external_checkout_redirect',
        version: 'surface_redirect_v1',
        distributionMode: 'Custom distribution',
        accessPolicyRef: 'shopify_access_lavenderlabs_2026_07',
        merchantAuthorizationRef: 'merchant_auth_lavenderlabs_v2',
        planEligibilityRef: 'plan_eligibility_lavenderlabs_2026_07',
        appEmbedVerificationRef: 'embed_verify_dawn_v15_2_asset_1_4_2',
        checkoutOrigin: 'https://checkout.lavenderlabs.co',
        targetRegions: ['CA', 'US'],
      },
      publishedAt: '8 min ago',
      hostedTraffic: 85,
      nativeTraffic: 15,
      audience: {
        label: 'US & CA · cart over $60 · returning customers',
        priority: 10,
        conflictPolicy: 'first_match_by_priority',
        eligibilityRules: [
          'Market is United States or Canada',
          'Cart total is at least $60',
          'Customer has placed at least 1 order',
        ],
      },
      allocation: { hosted: 85, native: 15, allocationVersion: 4, bucketSeed: 'bucket_sleep_reset_v1' },
      nodes: [
        { nodeId: 'shopify-cart', kind: 'entry', pageId: null, pinnedVersion: null, pinnedVersionId: null, offerRuleRef: null, recommendationRuleRef: null },
        { nodeId: 'checkout-main', kind: 'checkout', pageId: 'page-aura-checkout', pinnedVersion: 12, pinnedVersionId: 'pv_checkout_12', offerRuleRef: null, recommendationRuleRef: null },
        { nodeId: 'upsell-night', kind: 'upsell', pageId: 'page-night-routine', pinnedVersion: 8, pinnedVersionId: 'pv_upsell_8', offerRuleRef: 'offer_night_routine_v3', recommendationRuleRef: 'recommend_sleep_bundle_v2' },
        { nodeId: 'downsell-travel', kind: 'downsell', pageId: 'page-travel-fallback', pinnedVersion: 5, pinnedVersionId: 'pv_downsell_5', offerRuleRef: 'offer_travel_fallback_v2', recommendationRuleRef: 'recommend_travel_size_v1' },
        { nodeId: 'thankyou-main', kind: 'thank-you', pageId: 'page-aura-thankyou', pinnedVersion: 10, pinnedVersionId: 'pv_thankyou_10', offerRuleRef: null, recommendationRuleRef: null },
        { nodeId: 'shopify-native-checkout', kind: 'fallback', pageId: null, pinnedVersion: null, pinnedVersionId: null, offerRuleRef: null, recommendationRuleRef: null },
      ],
      graphEdges: [
        { from: 'shopify-cart', to: 'checkout-main', outcome: 'eligible_hosted_bucket' },
        { from: 'shopify-cart', to: 'shopify-native-checkout', outcome: 'native_control_or_fallback' },
        { from: 'checkout-main', to: 'upsell-night', outcome: 'checkout_completed_offer_eligible' },
        { from: 'checkout-main', to: 'thankyou-main', outcome: 'offer_ineligible_or_skipped' },
        { from: 'upsell-night', to: 'thankyou-main', outcome: 'accepted' },
        { from: 'upsell-night', to: 'downsell-travel', outcome: 'declined' },
        { from: 'upsell-night', to: 'thankyou-main', outcome: 'unavailable_or_skipped' },
        { from: 'downsell-travel', to: 'thankyou-main', outcome: 'accepted' },
        { from: 'downsell-travel', to: 'thankyou-main', outcome: 'declined' },
        { from: 'downsell-travel', to: 'thankyou-main', outcome: 'unavailable_or_skipped' },
      ],
      paymentRoute: {
        policyRef: 'payroute_primary_2026_07',
        checkoutCurrency: 'USD',
        connectionRefs: [
          { providerId: 'airwallex', connectionRef: 'provider_connection_airwallex' },
          { providerId: 'paypal', connectionRef: 'provider_connection_paypal' },
          { providerId: 'stripe', connectionRef: 'provider_connection_stripe' },
        ],
        bindings: PAYMENT_ROUTE_BINDINGS,
        requiredMethods: ['card', 'paypal'],
        capabilityDimensions: ['payment_method', 'region', 'currency', 'authorization_state'],
      },
      cartHandoffContract: {
        schemaVersion: 'bestcheckout.cart-handoff.v1',
        requiredFields: ['variant_id', 'quantity', 'line_properties', 'selling_plan', 'market', 'currency', 'discounts', 'shipping', 'tax', 'duty'],
        authoritativeRefresh: 'required_before_payment',
        ttlSeconds: 300,
      },
      postPurchaseCapabilityPolicyRef: 'postpurchase_runtime_v2',
      fallbackPolicy: { ref: 'phase_aware_checkout_recovery_v2', preCharge: 'shopify_native_checkout', paymentUnknown: 'query_provider_then_resume', captured: 'finalize_reconcile_or_refund' },
      trackingContractVersion: 'bestcheckout.tracking.v1',
      trackingContract: { version: 'bestcheckout.tracking.v1', destinationIds: ['bestcheckout'] },
      writebackPolicy: { circuitBreakerRef: 'writeback_breaker_v2', maxBacklog: 25, maxAgeMinutes: 10, onOpen: 'new_hosted_sessions_to_native_existing_payments_reconcile' },
      hashAlgorithm: 'prototype-fnv1a32',
      checkedPayloadHash: 'payload_sleep_reset_12',
      idempotencyKey: 'publish:funnel-sleep-reset:fr_funnel-sleep-reset_12:payload_sleep_reset_12',
    },
  },
  {
    id: 'funnel-new-customer',
    name: 'New customer starter',
    status: FUNNEL_STATUS.DRAFT,
    priority: 20,
    conflictPolicy: 'first_match_by_priority',
    audience: 'First-time customers · United States',
    hostedTraffic: 0,
    nativeTraffic: 100,
    sessions: '—',
    conversion: '—',
    aov: '—',
    revenue: '—',
    updated: 'Yesterday',
    rules: ['Market is United States', 'Customer has placed 0 orders'],
    audienceConditions: [
      { field: 'customer_type', operator: 'is', value: 'New customer' },
      { field: 'country', operator: 'is', value: 'United States' },
    ],
    draftRevisionSequence: 3,
    draftRevisionId: 'fr_funnel-new-customer_3',
    allocationVersion: 1,
    bucketSeed: 'bucket_new_customer_v1',
    paymentRoutePolicyRef: 'payroute_primary_2026_07',
    paymentRouteProviderIds: ['stripe', 'airwallex', 'paypal'],
    paymentRouteBindings: PAYMENT_ROUTE_BINDINGS,
    requiredPaymentMethods: ['card', 'paypal'],
    postPurchaseCapabilityPolicyRef: 'postpurchase_runtime_v2',
    fallbackPolicyRef: 'phase_aware_checkout_recovery_v2',
    trackingContractVersion: 'bestcheckout.tracking.v1',
    nodes: [
      { id: 'shopify-cart', kind: 'entry', label: 'Shopify cart', detail: 'Eligible traffic', state: 'Ready' },
      { id: 'checkout-express', kind: 'checkout', label: 'Express checkout', detail: 'Draft revision only', pageId: 'page-express-checkout', state: 'Draft' },
      { id: 'thankyou-main', kind: 'thank-you', label: 'Aura thank you', detail: 'Ready to pin on first publish', pageId: 'page-aura-thankyou', state: 'Ready' },
    ],
    graphEdges: [
      { from: 'shopify-cart', to: 'checkout-express', outcome: 'eligible_hosted_bucket' },
      { from: 'shopify-cart', to: 'shopify-native-checkout', outcome: 'native_control_or_fallback' },
      { from: 'checkout-express', to: 'thankyou-main', outcome: 'checkout_completed' },
    ],
    guardrails: {
      traffic: 'Not evaluated',
      pages: 'Not evaluated',
      graph: 'Not evaluated',
      payment: 'Not evaluated',
      inventory: 'Not evaluated',
      tracking: 'Not evaluated',
      writeback: 'Not evaluated',
      shopifyAccess: 'Not evaluated',
      domain: 'Not evaluated',
      embed: 'Not evaluated',
      fallback: 'Shopify native before payment',
    },
    guardrailSeverity: { traffic: 'block', pages: 'block', graph: 'block', payment: 'block', inventory: 'block', tracking: 'warn', writeback: 'block', shopifyAccess: 'block', domain: 'block', embed: 'block' },
    deploymentCheck: null,
    runtimeTraffic: { hosted: 0, native: 100 },
    currentDeploymentId: null,
    deploymentHistory: [],
    deploymentSnapshot: null,
  },
  {
    id: 'funnel-refill',
    name: 'Refill recovery',
    status: FUNNEL_STATUS.PAUSED,
    priority: 30,
    conflictPolicy: 'first_match_by_priority',
    audience: 'Repeat buyers · 30+ days since last order',
    hostedTraffic: 70,
    nativeTraffic: 30,
    sessions: '4,290',
    conversion: '4.16%',
    aov: '$68.40',
    revenue: '$12,244',
    updated: 'Jul 13',
    rules: ['Customer has placed at least 2 orders', 'Last order was 30+ days ago'],
    audienceConditions: [
      { field: 'past_orders', operator: 'at_least', value: '2' },
      { field: 'last_order', operator: 'at_least', value: '30 days ago' },
    ],
    draftRevisionSequence: 8,
    draftRevisionId: 'fr_funnel-refill_8',
    allocationVersion: 3,
    bucketSeed: 'bucket_refill_v1',
    paymentRoutePolicyRef: 'payroute_primary_2026_07',
    paymentRouteProviderIds: ['stripe', 'airwallex', 'paypal'],
    paymentRouteBindings: PAYMENT_ROUTE_BINDINGS,
    requiredPaymentMethods: ['card', 'paypal'],
    postPurchaseCapabilityPolicyRef: 'postpurchase_runtime_v2',
    fallbackPolicyRef: 'phase_aware_checkout_recovery_v2',
    trackingContractVersion: 'bestcheckout.tracking.v1',
    nodes: [
      { id: 'shopify-cart', kind: 'entry', label: 'Shopify cart', detail: 'Eligible traffic', state: 'Ready' },
      { id: 'checkout-main', kind: 'checkout', label: 'Aura checkout', detail: 'Saved draft matches paused deployment', pageId: 'page-aura-checkout', state: 'Ready' },
      { id: 'upsell-night', kind: 'upsell', label: 'Night routine offer', detail: 'Saved draft matches paused deployment', pageId: 'page-night-routine', state: 'Ready', offerRuleRef: 'offer_refill_v2', recommendationRuleRef: 'recommend_sleep_bundle_v2' },
      { id: 'thankyou-main', kind: 'thank-you', label: 'Aura thank you', detail: 'Saved draft matches paused deployment', pageId: 'page-aura-thankyou', state: 'Ready' },
    ],
    graphEdges: [
      { from: 'shopify-cart', to: 'checkout-main', outcome: 'eligible_hosted_bucket' },
      { from: 'shopify-cart', to: 'shopify-native-checkout', outcome: 'native_control_or_fallback' },
      { from: 'checkout-main', to: 'upsell-night', outcome: 'checkout_completed_offer_eligible' },
      { from: 'checkout-main', to: 'thankyou-main', outcome: 'offer_ineligible_or_skipped' },
      { from: 'upsell-night', to: 'thankyou-main', outcome: 'accepted' },
      { from: 'upsell-night', to: 'thankyou-main', outcome: 'declined' },
      { from: 'upsell-night', to: 'thankyou-main', outcome: 'unavailable_or_skipped' },
    ],
    guardrails: {
      traffic: 'Not evaluated',
      pages: 'Ready',
      graph: 'Ready',
      payment: 'Ready',
      inventory: 'Action required',
      tracking: 'Ready',
      writeback: 'Ready',
      shopifyAccess: 'Ready',
      domain: 'Ready',
      embed: 'Ready',
      fallback: 'Shopify native before payment',
    },
    guardrailSeverity: { traffic: 'block', pages: 'block', graph: 'block', payment: 'block', inventory: 'block', tracking: 'warn', writeback: 'block', shopifyAccess: 'block', domain: 'block', embed: 'block' },
    deploymentCheck: { expectedRevision: 'fr_funnel-refill_7', checkedPayloadHash: 'payload_refill_7', snapshotHash: 'payload_refill_7', idempotencyKey: 'publish:funnel-refill:fr_funnel-refill_7:payload_refill_7', checkedAt: 'Jul 13' },
    runtimeTraffic: { hosted: 0, native: 100 },
    currentDeploymentId: 'deploy_refill_7',
    deploymentHistory: [],
    deploymentSnapshot: {
      schemaVersion: 'bestcheckout.funnel-deployment.v1',
      id: 'deploy_refill_7',
      sourceFunnelRevision: 'fr_funnel-refill_7',
      sourceFunnelRevisionSequence: 7,
      surface: {
        mode: 'external_checkout_redirect',
        version: 'surface_redirect_v1',
        distributionMode: 'Custom distribution',
        accessPolicyRef: 'shopify_access_lavenderlabs_2026_07',
        merchantAuthorizationRef: 'merchant_auth_lavenderlabs_v2',
        planEligibilityRef: 'plan_eligibility_lavenderlabs_2026_07',
        appEmbedVerificationRef: 'embed_verify_dawn_v15_2_asset_1_4_2',
        checkoutOrigin: 'https://checkout.lavenderlabs.co',
        targetRegions: ['CA', 'US'],
      },
      publishedAt: 'Jul 13',
      hostedTraffic: 70,
      nativeTraffic: 30,
      audience: {
        label: 'Repeat buyers · 30+ days since last order',
        priority: 30,
        conflictPolicy: 'first_match_by_priority',
        eligibilityRules: ['Customer has placed at least 2 orders', 'Last order was 30+ days ago'],
      },
      allocation: { hosted: 70, native: 30, allocationVersion: 2, bucketSeed: 'bucket_refill_v1' },
      nodes: [
        { nodeId: 'shopify-cart', kind: 'entry', pageId: null, pinnedVersion: null, pinnedVersionId: null, offerRuleRef: null, recommendationRuleRef: null },
        { nodeId: 'checkout-main', kind: 'checkout', pageId: 'page-aura-checkout', pinnedVersion: 12, pinnedVersionId: 'pv_checkout_12', offerRuleRef: null, recommendationRuleRef: null },
        { nodeId: 'upsell-night', kind: 'upsell', pageId: 'page-night-routine', pinnedVersion: 8, pinnedVersionId: 'pv_upsell_8', offerRuleRef: 'offer_refill_v2', recommendationRuleRef: 'recommend_sleep_bundle_v2' },
        { nodeId: 'thankyou-main', kind: 'thank-you', pageId: 'page-aura-thankyou', pinnedVersion: 10, pinnedVersionId: 'pv_thankyou_10', offerRuleRef: null, recommendationRuleRef: null },
        { nodeId: 'shopify-native-checkout', kind: 'fallback', pageId: null, pinnedVersion: null, pinnedVersionId: null, offerRuleRef: null, recommendationRuleRef: null },
      ],
      graphEdges: [
        { from: 'shopify-cart', to: 'checkout-main', outcome: 'eligible_hosted_bucket' },
        { from: 'shopify-cart', to: 'shopify-native-checkout', outcome: 'native_control_or_fallback' },
        { from: 'checkout-main', to: 'upsell-night', outcome: 'checkout_completed_offer_eligible' },
        { from: 'checkout-main', to: 'thankyou-main', outcome: 'offer_ineligible_or_skipped' },
        { from: 'upsell-night', to: 'thankyou-main', outcome: 'accepted' },
        { from: 'upsell-night', to: 'thankyou-main', outcome: 'declined' },
        { from: 'upsell-night', to: 'thankyou-main', outcome: 'unavailable_or_skipped' },
      ],
      paymentRoute: {
        policyRef: 'payroute_primary_2026_07',
        checkoutCurrency: 'USD',
        connectionRefs: [
          { providerId: 'airwallex', connectionRef: 'provider_connection_airwallex' },
          { providerId: 'paypal', connectionRef: 'provider_connection_paypal' },
          { providerId: 'stripe', connectionRef: 'provider_connection_stripe' },
        ],
        bindings: PAYMENT_ROUTE_BINDINGS,
        requiredMethods: ['card', 'paypal'],
        capabilityDimensions: ['payment_method', 'region', 'currency', 'authorization_state'],
      },
      cartHandoffContract: {
        schemaVersion: 'bestcheckout.cart-handoff.v1',
        requiredFields: ['variant_id', 'quantity', 'line_properties', 'selling_plan', 'market', 'currency', 'discounts', 'shipping', 'tax', 'duty'],
        authoritativeRefresh: 'required_before_payment',
        ttlSeconds: 300,
      },
      postPurchaseCapabilityPolicyRef: 'postpurchase_runtime_v2',
      fallbackPolicy: { ref: 'phase_aware_checkout_recovery_v2', preCharge: 'shopify_native_checkout', paymentUnknown: 'query_provider_then_resume', captured: 'finalize_reconcile_or_refund' },
      trackingContractVersion: 'bestcheckout.tracking.v1',
      trackingContract: { version: 'bestcheckout.tracking.v1', destinationIds: ['bestcheckout'] },
      writebackPolicy: { circuitBreakerRef: 'writeback_breaker_v2', maxBacklog: 25, maxAgeMinutes: 10, onOpen: 'new_hosted_sessions_to_native_existing_payments_reconcile' },
      hashAlgorithm: 'prototype-fnv1a32',
      checkedPayloadHash: 'payload_refill_7',
      idempotencyKey: 'publish:funnel-refill:fr_funnel-refill_7:payload_refill_7',
    },
  },
];

const PROVIDERS = [
  {
    id: 'stripe',
    name: 'Stripe',
    status: PROVIDER_STATUS.CONNECTED,
    account: 'acct_•••• 4821',
    methods: 'Cards · Apple Pay · Google Pay',
    regions: 'US, CA, GB, EU',
    postPurchase: CAPABILITY.CONDITIONAL,
    capabilityCoverage: '78% one-click · 14% confirm · 8% skip',
    notes: 'Off-session confirmation depends on the original payment method and mandate.',
    successRate: '98.7%',
    capabilityEvaluations: [
      { method: 'Card', region: 'US', currency: 'USD', authorizationState: 'Reusable mandate', outcome: CAPABILITY.SUPPORTED, confirmationFlow: 'One-click', reasonCode: 'mandate_ready', verifiedAt: 'Today, 09:18' },
      { method: 'Apple Pay', region: 'US', currency: 'USD', authorizationState: 'Wallet credential', outcome: CAPABILITY.CONDITIONAL, confirmationFlow: 'Provider confirmation', reasonCode: 'wallet_reconfirm', verifiedAt: 'Today, 09:18' },
    ],
  },
  {
    id: 'airwallex',
    name: 'Airwallex',
    status: PROVIDER_STATUS.CONNECTED,
    account: 'Lavender Labs US',
    methods: 'Cards · Apple Pay · Google Pay',
    regions: 'US, GB, EU, AU, SG',
    postPurchase: CAPABILITY.CONDITIONAL,
    capabilityCoverage: '71% one-click · 18% confirm · 11% skip',
    notes: 'Capability is evaluated by payment method, region and currency at runtime.',
    successRate: '98.2%',
    capabilityEvaluations: [
      { method: 'Card', region: 'GB', currency: 'GBP', authorizationState: 'Reusable mandate', outcome: CAPABILITY.SUPPORTED, confirmationFlow: 'One-click', reasonCode: 'merchant_initiated_ready', verifiedAt: 'Today, 09:11' },
      { method: 'Google Pay', region: 'SG', currency: 'SGD', authorizationState: 'Wallet credential', outcome: CAPABILITY.CONDITIONAL, confirmationFlow: 'Provider confirmation', reasonCode: 'wallet_reconfirm', verifiedAt: 'Today, 09:11' },
    ],
  },
  {
    id: 'paypal',
    name: 'PayPal',
    status: PROVIDER_STATUS.CONNECTED,
    account: 'payments@lavenderlabs.co',
    methods: 'PayPal wallet',
    regions: 'Global · eligible markets',
    postPurchase: CAPABILITY.CONDITIONAL,
    capabilityCoverage: '0% one-click · 64% confirm · 36% skip',
    notes: 'Merchant-initiated order changes require an eligible authorization flow.',
    successRate: '97.1%',
    capabilityEvaluations: [
      { method: 'PayPal wallet', region: 'US', currency: 'USD', authorizationState: 'Order authorization', outcome: CAPABILITY.CONDITIONAL, confirmationFlow: 'PayPal confirmation', reasonCode: 'reauthorization_required', verifiedAt: 'Today, 08:56' },
    ],
  },
  {
    id: 'nmi',
    name: 'NMI',
    status: PROVIDER_STATUS.PLANNED,
    account: 'Not connected',
    methods: 'Cards',
    regions: 'By gateway account',
    postPurchase: CAPABILITY.PLANNED,
    capabilityCoverage: 'Not evaluated',
    notes: 'Planned connector; capability contract must be verified before launch.',
    successRate: '—',
    capabilityEvaluations: [
      { method: 'Card', region: 'Merchant account', currency: 'Account currency', authorizationState: 'Unknown', outcome: CAPABILITY.PLANNED, confirmationFlow: 'Not defined', reasonCode: 'connector_planned', verifiedAt: 'Not verified' },
    ],
  },
  {
    id: 'klarna',
    name: 'Klarna',
    status: PROVIDER_STATUS.PLANNED,
    account: 'Not connected',
    methods: 'Buy now, pay later',
    regions: 'Eligible Klarna markets',
    postPurchase: CAPABILITY.NOT_SUPPORTED,
    capabilityCoverage: '0% eligible · safe skip',
    notes: 'Do not show a one-click post-purchase offer unless the method explicitly supports it.',
    successRate: '—',
    capabilityEvaluations: [
      { method: 'Klarna BNPL', region: 'US', currency: 'USD', authorizationState: 'Completed BNPL order', outcome: CAPABILITY.NOT_SUPPORTED, confirmationFlow: 'Safe skip', reasonCode: 'method_not_appendable', verifiedAt: 'Policy baseline' },
    ],
  },
  {
    id: 'checkout-com',
    name: 'Checkout.com',
    status: PROVIDER_STATUS.PLANNED,
    account: 'Not connected',
    methods: 'Cards · wallets',
    regions: 'By merchant entity',
    postPurchase: CAPABILITY.PLANNED,
    capabilityCoverage: 'Not evaluated',
    notes: 'Planned connector with method-level capability discovery.',
    successRate: '—',
    capabilityEvaluations: [
      { method: 'Card', region: 'Merchant entity', currency: 'Entity currency', authorizationState: 'Unknown', outcome: CAPABILITY.PLANNED, confirmationFlow: 'Not defined', reasonCode: 'connector_planned', verifiedAt: 'Not verified' },
    ],
  },
  {
    id: 'braintree',
    name: 'Braintree',
    status: PROVIDER_STATUS.PLANNED,
    account: 'Not connected',
    methods: 'Cards · PayPal · wallets',
    regions: 'Eligible Braintree markets',
    postPurchase: CAPABILITY.PLANNED,
    capabilityCoverage: 'Not evaluated',
    notes: 'Vault and merchant-account rules must be evaluated per transaction.',
    successRate: '—',
    capabilityEvaluations: [
      { method: 'Vaulted card', region: 'US', currency: 'USD', authorizationState: 'Unknown vault state', outcome: CAPABILITY.PLANNED, confirmationFlow: 'Not defined', reasonCode: 'connector_planned', verifiedAt: 'Not verified' },
    ],
  },
];

const TRACKING_CONNECTIONS = [
  {
    id: 'meta',
    name: 'Meta Pixel',
    discoveredId: '1287•••••042',
    discoveredFrom: 'Theme HTML',
    discoveryState: 'Discovered',
    ownershipState: 'Unconfirmed',
    browserConfigState: 'Candidate',
    serverAuthState: 'Not authorized',
    consentState: 'Needs review',
    testState: 'Not run',
    state: 'Action required',
  },
  {
    id: 'ga4',
    name: 'Google Analytics 4',
    discoveredId: 'G-4N••••J2',
    discoveredFrom: 'Theme HTML',
    discoveryState: 'Discovered',
    ownershipState: 'Unconfirmed',
    browserConfigState: 'Candidate',
    serverAuthState: 'Not applicable',
    consentState: 'Needs review',
    testState: 'Not run',
    state: 'Review',
  },
  {
    id: 'gtm',
    name: 'Google Tag Manager',
    discoveredId: 'GTM-N••••6Q',
    discoveredFrom: 'Theme HTML',
    discoveryState: 'Discovered',
    ownershipState: 'Unconfirmed',
    browserConfigState: 'Candidate',
    serverAuthState: 'Container-owned',
    consentState: 'Needs review',
    testState: 'Not run',
    state: 'Action required',
  },
  {
    id: 'bestcheckout',
    name: 'BestCheckout events',
    discoveredId: 'Managed by app',
    discoveredFrom: 'App pixel + server',
    discoveryState: 'Managed',
    ownershipState: 'App-owned',
    browserConfigState: 'Connected',
    serverAuthState: 'Connected',
    consentState: 'Customer Privacy API',
    testState: 'Passed',
    state: 'Healthy',
  },
];

const ACTIVITY = [
  {
    id: 'evt-003',
    category: 'payment',
    title: 'Checkout payment captured',
    detail: '$78.60 USD captured through Stripe for Sleep Reset funnel.',
    status: 'Succeeded',
    actor: 'Stripe webhook',
    time: '5 min ago',
    reference: 'pay_6df3',
    phase: 'base_payment_captured',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Base order open for post-purchase resolution',
  },
  {
    id: 'evt-002',
    category: 'post-purchase',
    title: 'Upsell accepted and appended',
    detail: 'Nighttime Gummies added through Stripe. Original order remained valid throughout.',
    status: 'Succeeded',
    actor: 'Payment orchestration',
    time: '4 min ago',
    reference: 'pi_•••• 7942',
    phase: 'additional_charge_succeeded',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Additional charge recorded; reconciliation required until snapshot finalizes',
  },
  {
    id: 'evt-snapshot',
    category: 'writeback',
    title: 'Final Order Snapshot finalized',
    detail: 'Snapshot snap_10482_v3 finalized at $97.80 USD with base and additional transaction references.',
    status: 'Succeeded',
    actor: 'Order finalization service',
    time: '3 min ago',
    reference: 'snap_10482_v3',
    phase: 'snapshot_finalized',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Immutable snapshot created; downstream projections may retry independently',
  },
  {
    id: 'evt-004',
    category: 'tracking',
    title: 'Purchase event deduplicated',
    detail: 'Browser and server events shared event_id evt_bc_10482; one purchase was delivered.',
    status: 'Succeeded',
    actor: 'Attribution service',
    time: '2 min ago',
    reference: 'evt_bc_10482',
    phase: 'purchase_delivered',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Purchase amount sourced from finalized snapshot',
  },
  {
    id: 'evt-001',
    category: 'writeback',
    title: 'Order #BC-10482 written back to Shopify',
    detail: 'ShopifyWritebackProjection linked snapshot snap_10482_v3 to Shopify order #12841 with 3 line items.',
    status: 'Succeeded',
    actor: 'BestCheckout system',
    time: '1 min ago',
    reference: 'ord_10482',
    phase: 'reconciled',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Projection reconciled without changing the immutable snapshot',
  },
  {
    id: 'evt-005',
    category: 'post-purchase',
    title: 'Post-purchase offer skipped safely',
    detail: 'PayPal authorization did not support an appended charge. Buyer continued to Thank you; original order was not changed.',
    status: 'Skipped',
    actor: 'Capability engine',
    time: '18 min ago',
    reference: 'ord_10477',
    phase: 'eligibility_skipped',
    attempt: 0,
    idempotency: 'Not applicable',
    integrity: 'No additional charge attempted; base paid order preserved',
  },
  {
    id: 'evt-006',
    category: 'sync',
    title: 'Shopify catalog delta synchronized',
    detail: '8 variants updated, 2 discounts refreshed and 1 shipping rate changed.',
    status: 'Succeeded',
    actor: 'products/update webhook',
    time: '24 min ago',
    reference: 'sync_8421',
    phase: 'catalog_delta_applied',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Commerce mapping updated without changing historical snapshots',
  },
  {
    id: 'evt-007',
    category: 'writeback',
    title: 'Order writeback retried',
    detail: 'First attempt timed out. Idempotency key returned the existing Shopify order on retry.',
    status: 'Recovered',
    actor: 'Reconciliation worker',
    time: '1 hr ago',
    reference: 'ord_10461',
    phase: 'writeback_pending → reconciled',
    attempt: 2,
    idempotency: 'Verified',
    integrity: 'Additional charge already succeeded; projection retried until reconciled',
  },
];

const PERFORMANCE_ROWS = {
  funnel: [
    { name: 'Sleep Reset', sessions: '12,840', conversion: '5.42%', aov: '$78.60', revenue: '$54,728', lift: '+18.4%' },
    { name: 'Refill recovery', sessions: '4,290', conversion: '4.16%', aov: '$68.40', revenue: '$12,244', lift: '+7.2%' },
    { name: 'Shopify native control', sessions: '2,310', conversion: '4.58%', aov: '$65.90', revenue: '$6,974', lift: 'Baseline' },
  ],
  page: [
    { name: 'Aura checkout', sessions: '12,840', conversion: '61.8%', aov: 'Completion', revenue: '$54,728', lift: '+4.2 pts' },
    { name: 'Night routine offer', sessions: '7,934', conversion: '18.6%', aov: 'Take rate', revenue: '$8,102', lift: '+2.8 pts' },
    { name: 'Travel size fallback', sessions: '2,184', conversion: '9.4%', aov: 'Recovery', revenue: '$1,306', lift: '+1.1 pts' },
    { name: 'Aura thank you', sessions: '8,616', conversion: '7.2%', aov: 'Referral CTR', revenue: '—', lift: '+0.6 pts' },
  ],
  provider: [
    { name: 'Stripe', sessions: '9,404', conversion: '98.7%', aov: 'Success rate', revenue: '$45,821', lift: '+0.4 pts' },
    { name: 'Airwallex', sessions: '3,821', conversion: '98.2%', aov: 'Success rate', revenue: '$19,108', lift: '+0.6 pts' },
    { name: 'PayPal', sessions: '2,215', conversion: '97.1%', aov: 'Success rate', revenue: '$9,017', lift: '-0.2 pts' },
  ],
  channel: [
    { name: 'Meta paid', sessions: '8,740', conversion: '5.63%', aov: '$79.40', revenue: '$39,128', lift: '+20.1%' },
    { name: 'Google paid', sessions: '4,106', conversion: '5.08%', aov: '$74.10', revenue: '$15,473', lift: '+14.8%' },
    { name: 'Direct / organic', sessions: '3,284', conversion: '4.71%', aov: '$69.80', revenue: '$10,826', lift: '+6.2%' },
    { name: 'Unattributed', sessions: '1,310', conversion: '3.92%', aov: '$66.30', revenue: '$3,404', lift: 'Review' },
  ],
};

const INSTALL_ACTIVITY = [
  {
    id: 'evt-install-007',
    category: 'payment',
    title: 'Payment route test passed',
    detail: 'Stripe card and PayPal authorization checks passed in test mode. No buyer payment was created.',
    status: 'Succeeded',
    actor: 'Payment route validator',
    time: 'Just now',
    reference: 'paytest_install_8f42',
    phase: 'payment_route_validated',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Test-only validation; buyer traffic remains disabled until a Funnel is published.',
  },
  {
    id: 'evt-install-006',
    category: 'post-purchase',
    title: 'Post-purchase eligibility validated',
    detail: 'The first offer rule and fallback path were validated without creating an additional charge.',
    status: 'Skipped',
    actor: 'Offer eligibility service',
    time: 'Just now',
    reference: 'offercheck_install_8f42',
    phase: 'post_purchase_test_skipped',
    attempt: 0,
    idempotency: 'Not applicable',
    integrity: 'No buyer order or payment was modified during setup validation.',
  },
  {
    id: 'evt-install-005',
    category: 'tracking',
    title: 'Browser and server event test passed',
    detail: 'The app pixel and server destination shared one test event ID; one test purchase event was retained.',
    status: 'Succeeded',
    actor: 'Attribution service',
    time: 'Just now',
    reference: 'evt_test_install_8f42',
    phase: 'tracking_contract_verified',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Test event only; production conversion reporting begins after hosted Checkout traffic.',
  },
  {
    id: 'evt-install-004',
    category: 'writeback',
    title: 'Shopify writeback dry run verified',
    detail: 'The order projection contract and idempotency key were validated without creating a Shopify order.',
    status: 'Succeeded',
    actor: 'Shopify writeback validator',
    time: 'Just now',
    reference: 'writebacktest_install_8f42',
    phase: 'writeback_contract_verified',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Dry run only; a real order is written back only after payment and final snapshot completion.',
  },
  {
    id: 'evt-install-003',
    category: 'sync',
    title: 'Initial catalog synchronized',
    detail: '248 products, 816 variants, 14 discounts and 22 shipping rates were mapped during authorization.',
    status: 'Succeeded',
    actor: 'BestCheckout setup',
    time: 'Just now',
    reference: 'sync_install_8f42',
    phase: 'initial_commerce_import',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'No buyer traffic is routed to BestCheckout until a Funnel is published.',
  },
  {
    id: 'evt-install-002',
    category: 'sync',
    title: 'Checkout workspace created',
    detail: 'The BestShopio store, checkout workspace and Shopify ID mapping were provisioned automatically.',
    status: 'Succeeded',
    actor: 'BestCheckout setup',
    time: 'Just now',
    reference: 'workspace_bs_store_8f42',
    phase: 'workspace_provisioned',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Initial templates remain drafts and cannot receive traffic.',
  },
  {
    id: 'evt-install-001',
    category: 'sync',
    title: 'Shopify access authorized',
    detail: 'Required scopes for products, discounts, shipping and order writeback were verified.',
    status: 'Succeeded',
    actor: 'Shopify authorization',
    time: '1 min ago',
    reference: 'auth_lavenderlabs_01',
    phase: 'shopify_authorized',
    attempt: 1,
    idempotency: 'Verified',
    integrity: 'Buyer Checkout continues through Shopify native Checkout by default.',
  },
];

function draftTemplatePage(page) {
  return Object.assign({}, page, {
    status: 'Draft',
    version: 0,
    publishedVersionId: null,
    revisionSequence: 1,
    draftRevisionId: 'rev_' + page.id + '_1',
    draftRevision: 1,
    updated: 'Created during installation',
    metric: '—',
    change: 'Not live',
  });
}

function draftInstallFunnel(funnel) {
  const nodes = funnel.nodes.map(function (node) {
    if (node.kind === 'entry') return Object.assign({}, node, { detail: 'Draft audience is ready to configure', state: 'Ready' });
    const detail = ['upsell', 'downsell'].includes(node.kind)
      ? 'Draft page and offer rule ready to configure'
      : 'Draft page ready to configure';
    return Object.assign({}, node, { detail: detail, state: 'Draft' });
  });
  return Object.assign({}, funnel, {
    status: FUNNEL_STATUS.DRAFT,
    hostedTraffic: 0,
    nativeTraffic: 100,
    sessions: '—',
    conversion: '—',
    aov: '—',
    revenue: '—',
    updated: 'Created during installation',
    nodes: nodes,
    guardrails: {
      traffic: 'Not evaluated',
      pages: 'Not evaluated',
      graph: 'Not evaluated',
      payment: 'Not evaluated',
      inventory: 'Not evaluated',
      tracking: 'Not evaluated',
      writeback: 'Not evaluated',
      shopifyAccess: 'Ready',
      domain: 'Not configured',
      embed: 'Ready',
      fallback: 'Shopify native before payment',
    },
    deploymentCheck: null,
    runtimeTraffic: { hosted: 0, native: 100 },
    runtimeOverride: null,
    currentDeploymentId: null,
    deploymentHistory: [],
    deploymentSnapshot: null,
  });
}

function installPaymentProvider(provider) {
  if (!['stripe', 'airwallex', 'paypal'].includes(provider.id)) return provider;
  return Object.assign({}, provider, {
    status: PROVIDER_STATUS.ACTION_REQUIRED,
    account: 'Not connected',
    postPurchase: CAPABILITY.NOT_EVALUATED,
    capabilityCoverage: 'Connect an account to evaluate',
    successRate: '—',
    capabilityEvaluations: provider.capabilityEvaluations.map(function (evaluation) {
      return Object.assign({}, evaluation, {
        authorizationState: 'Not connected',
        outcome: CAPABILITY.NOT_EVALUATED,
        confirmationFlow: 'Not evaluated',
        reasonCode: 'provider_not_connected',
        verifiedAt: 'Not verified',
      });
    }),
  });
}

function blankPerformanceRows(rows) {
  return Object.fromEntries(Object.entries(rows).map(function (entry) {
    return [entry[0], entry[1].map(function (row) {
      return Object.assign({}, row, { sessions: '—', conversion: '—', aov: '—', revenue: '—', lift: 'Not live' });
    })];
  }));
}

function publishDemoStore(state) {
  const primaryFunnel = state.funnels.find(function (funnel) { return funnel.id === 'funnel-sleep-reset'; });
  if (primaryFunnel) {
    primaryFunnel.status = FUNNEL_STATUS.LIVE;
    primaryFunnel.hostedTraffic = 85;
    primaryFunnel.nativeTraffic = 15;
    primaryFunnel.sessions = '12,840';
    primaryFunnel.conversion = '5.42%';
    primaryFunnel.aov = '$78.60';
    primaryFunnel.revenue = '$54,728';
    primaryFunnel.updated = 'Just now';
    primaryFunnel.runtimeTraffic = { hosted: 85, native: 15 };
    primaryFunnel.guardrails = Object.assign({}, primaryFunnel.guardrails, {
      traffic: 'Ready',
      pages: 'Ready',
      graph: 'Ready',
      payment: 'Ready',
      inventory: 'Ready',
      tracking: 'Ready',
      writeback: 'Ready',
      shopifyAccess: 'Ready',
      domain: 'Ready',
      embed: 'Ready',
    });
  }
  state.store.domainConnection = 'Connected';
  state.store.dnsProvider = 'Cloudflare';
  state.store.domainStatus = 'Verified';
  state.store.sslStatus = 'Active';
  state.store.lastSync = '2 min ago';
  state.tracking = state.tracking.map(function (item) {
    return Object.assign({}, item, {
      ownershipState: item.id === 'bestcheckout' ? 'App-owned' : 'Verified',
      browserConfigState: 'Connected',
      serverAuthState: 'Connected',
      consentState: 'Verified',
      testState: 'Passed',
      state: 'Healthy',
    });
  });
  state.launchChecks = [
    { id: 'shopifyAccess', label: 'Hosted checkout access approved', detail: 'Shopify access and active theme interception are verified.', state: 'Complete', route: 'settings?tab=diagnostics' },
    { id: 'sync', label: 'Store data synchronized', detail: 'Catalog, discounts and shipping data are current.', state: 'Complete', route: 'settings?tab=sync' },
    { id: 'domain', label: 'Checkout domain verified', detail: 'DNS and SSL are active on checkout.lavenderlabs.co.', state: 'Complete', route: 'settings?tab=domain' },
    { id: 'payments', label: 'Payment routes healthy', detail: 'Stripe, Airwallex and PayPal are connected.', state: 'Complete', route: 'settings?tab=payments' },
    { id: 'tracking', label: 'Conversion tracking healthy', detail: 'Browser and server delivery tests are passing.', state: 'Complete', route: 'settings?tab=attribution' },
    { id: 'launch', label: 'Sleep Reset funnel is live', detail: '85% of eligible buyers use BestCheckout; Shopify remains the control.', state: 'Complete', route: 'funnels/funnel-sleep-reset' },
  ];
  return state;
}

export function createMockBestCheckoutState(profile) {
  const demoProfile = profile === 'live' ? 'live' : 'installed';
  const initialState = {
    store: {
      name: 'Lavender Labs',
      myshopifyDomain: 'lavender-labs.myshopify.com',
      bestShopioStoreId: 'bs_store_8f42',
      appInstanceName: 'BestCheckout · Lavender Labs',
      appInstanceId: 'bc_lavender_labs_01',
      distributionMethod: 'Custom distribution',
      installationScope: 'Single store',
      status: 'Connected',
      appEmbed: 'Verified',
      domain: 'checkout.lavenderlabs.co',
      previewDomain: 'lavender-labs.preview.bestcheckout.app',
      domainStatus: 'Pending verification',
      sslStatus: 'Waiting for DNS',
      syncStatus: 'Healthy',
      lastSync: '24 min ago',
      products: 248,
      variants: 816,
      discounts: 14,
      shippingRates: 22,
      mappingCoverage: '100%',
      webhookHealth: '12 / 12 healthy',
      activeTheme: 'Dawn · v15.2.0',
      embedAsset: 'bestcheckout-embed · v1.4.2',
      embedVerifiedAt: 'Today, 09:42',
      appEmbedVerificationRef: 'embed_verify_dawn_v15_2_asset_1_4_2',
      embedEntryChecks: [
        { target: 'Cart page', state: 'Verified' },
        { target: 'Cart drawer', state: 'Verified' },
        { target: 'Buy now', state: 'Verified' },
        { target: 'Third-party cart button', state: 'Verified' },
        { target: 'Cart payload parity', state: 'Verified' },
      ],
      distributionMode: 'Custom distribution',
      distributionStatus: 'Approved',
      checkoutSurfaceMode: 'external_checkout_redirect',
      checkoutSurfaceVersion: 'surface_redirect_v1',
      checkoutSurfaceAuthorization: 'Approved',
      shopifyAccessPolicyRef: 'shopify_access_lavenderlabs_2026_07',
      merchantAuthorization: 'Verified',
      merchantAuthorizationRef: 'merchant_auth_lavenderlabs_v2',
      shopifyPlan: 'Shopify Plus',
      planEligibility: 'Eligible',
      planEligibilityRef: 'plan_eligibility_lavenderlabs_2026_07',
      targetRegions: ['US', 'CA'],
      checkoutCurrency: 'USD',
      regionEligibility: 'Eligible',
      cartHandoffSchemaVersion: 'bestcheckout.cart-handoff.v1',
      cartHandoffTtlSeconds: 300,
      cartHandoffValidation: 'Healthy',
      authoritativePriceRefresh: 'Healthy',
      writebackCircuitBreakerRef: 'writeback_breaker_v2',
      writebackCreateSuccessRate: 99.98,
      writebackBacklog: 0,
      writebackOldestAgeMinutes: 0,
      writebackMaxBacklog: 25,
      writebackMaxAgeMinutes: 10,
      writebackCircuitState: 'Closed',
      writebackCircuitOpenedAt: null,
      newHostedSessionsPolicy: 'Allowed',
    },
    pages: structuredClone(PAGE_ASSETS),
    funnels: structuredClone(FUNNELS),
    offerVersions: structuredClone(OFFER_VERSIONS),
    recommendationRuleVersions: structuredClone(RECOMMENDATION_RULE_VERSIONS),
    offerCatalogVariants: structuredClone(OFFER_CATALOG_VARIANTS),
    offerSourceProducts: structuredClone(OFFER_SOURCE_PRODUCTS),
    providers: structuredClone(PROVIDERS),
    tracking: structuredClone(TRACKING_CONNECTIONS),
    activity: structuredClone(ACTIVITY),
    performanceRows: structuredClone(PERFORMANCE_ROWS),
    metrics: {
      gmv: { value: '$73,946', delta: '+18.1%', helper: 'BestCheckout attributed GMV' },
      conversion: { value: '5.42%', delta: '+0.84 pts', helper: 'vs Shopify native control' },
      aov: { value: '$78.60', delta: '+19.3%', helper: 'including post-purchase' },
      recovered: { value: '$9,408', delta: '+12.6%', helper: 'upsell and downsell revenue' },
    },
    launchChecks: [
      { id: 'shopifyAccess', label: 'Hosted checkout access approved', detail: 'Distribution, merchant authorization and target regions are verified for this store.', state: 'Complete', route: 'settings?tab=diagnostics' },
      { id: 'sync', label: 'Store data synchronized', detail: 'Products, discounts and shipping are current.', state: 'Complete', route: 'settings?tab=sync' },
      { id: 'domain', label: 'Checkout domain verified', detail: 'SSL is active on checkout.lavenderlabs.co.', state: 'Complete', route: 'settings?tab=domain' },
      { id: 'payments', label: 'Payment routes healthy', detail: 'Stripe, Airwallex and PayPal are connected.', state: 'Complete', route: 'settings?tab=payments' },
      { id: 'tracking', label: 'Review discovered tracking tags', detail: 'Meta and GTM need consent and server-event authorization review.', state: 'Action required', route: 'settings?tab=attribution' },
      { id: 'embed', label: 'App embed verified', detail: 'Verified against the current active theme and asset version.', state: 'Complete', route: 'settings?tab=embed' },
      { id: 'writeback', label: 'Order writeback tested', detail: 'Idempotency and reconciliation checks passed.', state: 'Complete', route: 'settings?tab=diagnostics' },
    ],
    chart: [42, 45, 44, 49, 52, 51, 56, 55, 60, 62, 64, 68, 67, 72],
    ui: {
      locale: 'en',
      languageOpen: false,
      storeMenuOpen: false,
      demoProfile: demoProfile,
      activeFunnelId: 'funnel-sleep-reset',
      activeNodeId: 'checkout-main',
      funnelStatusFilter: 'all',
      pageTypeFilter: 'all',
      activityFilter: 'all',
      performanceTab: 'funnel',
      performanceDateRange: '14d',
      editorDevice: 'desktop',
      editorSection: 'brand',
      editorDirty: false,
      focusMode: null,
      canvasZoom: 1,
      previewFunnelStep: 'checkout',
      domainSetupMode: 'automatic',
      publishIntent: null,
      diagnosticsRanAt: 'Today, 09:40',
    },
  };

  if (demoProfile === 'live') return publishDemoStore(initialState);

  initialState.pages = initialState.pages.map(draftTemplatePage);
  initialState.funnels = initialState.funnels.map(draftInstallFunnel);
  initialState.offerVersions = initialState.offerVersions.map(function (offer) { return Object.assign({}, offer, { status: 'Draft' }); });
  initialState.recommendationRuleVersions = initialState.recommendationRuleVersions.map(function (rule) { return Object.assign({}, rule, { status: 'Draft' }); });
  initialState.providers = initialState.providers.map(installPaymentProvider);
  initialState.activity = structuredClone(INSTALL_ACTIVITY);
  initialState.performanceRows = blankPerformanceRows(initialState.performanceRows);
  initialState.metrics = {
    gmv: { value: '—', delta: 'Not live', helper: 'Appears after the first published Funnel' },
    conversion: { value: '—', delta: 'Not live', helper: 'Appears after hosted Checkout traffic' },
    aov: { value: '—', delta: 'Not live', helper: 'Appears after completed orders' },
    recovered: { value: '—', delta: 'Not live', helper: 'Appears after post-purchase offers run' },
  };
  initialState.store.lastSync = 'Just now';
  initialState.store.domainConnection = 'Not connected';
  initialState.store.domainStatus = 'Pending connection';
  initialState.store.sslStatus = 'Waiting for DNS';
  initialState.launchChecks = [
    { id: 'shopifyAccess', label: 'Shopify access authorized', detail: 'Completed automatically during installation.', state: 'Complete', route: 'settings?tab=sync' },
    { id: 'sync', label: 'Store data synchronized', detail: 'Completed automatically during installation.', state: 'Complete', route: 'settings?tab=sync' },
    { id: 'pages', label: 'Initial templates created', detail: 'All templates are drafts until you publish a page version.', state: 'Action required', route: 'pages' },
    { id: 'domain', label: 'Checkout domain', detail: 'Connect DNS before publishing buyer traffic.', state: 'Action required', route: 'settings?tab=domain' },
    { id: 'payments', label: 'Payment routing', detail: 'Connect a merchant payment account before publishing.', state: 'Action required', route: 'settings?tab=payments' },
  ];
  return initialState;
}
